In [24]:
import pickle
import numpy as np 

In [25]:
ohe_sex=pickle.load(open('Model_ak/ohe_sex.pkl','rb'))
ohe_embarked=pickle.load(open('Model_ak/ohe_embarked.pkl','rb'))
clf=pickle.load(open('Model_ak/clf.pkl','rb'))

In [35]:
# assume user input Data
#pclass /gendr /age/sibsp/parch/Fare/Embarked
test_input=np.array([1, 'male' ,31.0 ,0 ,0 ,10.5 ,'S'],dtype=object).reshape(1,7)

In [45]:
test_input[:,2]

array([31.0], dtype=object)

In [46]:
test_input_sex=ohe_sex.transform(test_input[:,1].reshape(1,1))

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [47]:
test_input_sex

array([[0., 1.]])

In [48]:
test_input_embarked=ohe_embarked.transform(test_input[:,1].reshape(1,1))

In [49]:
test_input_age=test_input[:,2].reshape(1,1)

In [50]:
test_input_transformed=np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [51]:
test_input_transformed.shape

(1, 10)

In [52]:
clf.predict(test_input_transformed)

array([0], dtype=int64)

In [53]:
test_input[:,[0,3,4,5]]

array([[1, 0, 0, 10.5]], dtype=object)